default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER']  %>
  password: <%= ENV['DB_PASSWORD']  %>
  host: <%= ENV['DB_HOST']  %>

development:
  primary:
    <<: *default
    database: <%= ENV['DB_NAME_PRIMARY']  %>
    
  secondary:
    <<: *default
    database: <%= ENV['DB_NAME_SECONDARY']  %>
    database_tasks: false

