export const business_typeOptions = [
  'Education and healthcare services',
  'Accommodation and food services',
  'Retail trade',
  'Manufacturing',
  'Information technology',
  'Finance and insurance',
  'Construction',
  'Wholesale trade',
  'Transportation and warehousing',
  'Real estate and rental and leasing',
  'Professional, scientific, and technical services',
  'Administrative and support services',
  'Arts, entertainment, and recreation',
  'Agriculture, forestry, fishing, and hunting',
  'Mining, quarrying, and oil and gas extraction',
  'Utilities',
  'Public administration',
  'Other services (except public administration)',
];

export const statesRequiringBusinessType = [
  { name: 'Arkansas', code: 'AR' },
  { name: 'Georgia', code: 'GA' },
  { name: 'Kansas', code: 'KS' },
  { name: 'Indiana', code: 'IN' },
  { name: 'Kentucky', code: 'KY' },
  { name: 'Michigan', code: 'MI' },
  { name: 'Minnesota', code: 'MN' },
  { name: 'Nebraska', code: 'NE' },
  { name: 'Nevada', code: 'NV' },
  { name: 'New Jersey', code: 'NJ' },
  { name: 'North Carolina', code: 'NC' },
  { name: 'North Dakota', code: 'ND' },
  { name: 'Ohio', code: 'OH' },
  { name: 'Oklahoma', code: 'OK' },
  { name: 'Rhode Island', code: 'RI' },
  { name: 'South Dakota', code: 'SD' },
  { name: 'Tennessee', code: 'TN' },
  { name: 'Vermont', code: 'VT' },
  { name: 'Washington', code: 'WA' },
  { name: 'West Virginia', code: 'WV' },
  { name: 'Wisconsin', code: 'WI' },
  { name: 'Wyoming', code: 'WY' },
];
