export const certificateLabelOptions = [
    'Affidavit',
    'Auto-validation No Issues Found',
    'Certexpress Import',
    'Certexpress Public Upload',
    'Certexpress Upload',
    'Certificate Request',
    'Do Not Send To Api',
    'Drop Ship',
    'Ecommerce Upload',
    'Filled Online',
    'Filled Online Retail',
    'Filled Online Webportal',
    'Locked',
    'Multi-jurisdictional',
    'Public Wizard',
    'Retail Upload',
    'Revalidated',
  ];