export const exemption_reasonOptions = [
    'Agricultural',
    'Capital Improvement',
    'Charitable/Exempt Organization',
    'Common Carrier',
    'Direct Mail',
    'Direct Pay',
    'Enterprise Zone',
    'Exempt By Statute',
    'Exporters',
    'Federal Gov',
    'Foreign Diplomat',
    'Industrial Prod/manufacturers',
    'Local Government',
    'Material Purchase',
    'Medical',
    'Non-resident',
    'Other/custom',
    'Prime Contractor',
    'R&D',
    'Religious Org',
    'Religious/educational Org',
    'Resale',
    'State Goverment',
    'Tribal Government',
  ];